"""Update user constraints and FKs

Revision ID: 082a54adbf8b
Revises: 442c35b10eb2
Create Date: 2026-09-05 13:51:39.405052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082a54adbf8b'
down_revision: Union[str, Sequence[str], None] = '442c35b10eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.drop_column('users', 'team_id')
    op.create_check_constraint('check_customer_role', 'users', "role != 'customer' OR customer_id IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_customer_role', 'users', type_='check')
    op.add_column('users', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
